version: 2.1

orbs:
  ruby: circleci/ruby@1.1.2

jobs:
  automated_tests:
    docker:
      - image: cimg/ruby:3.2.0
    steps:
      - checkout
      - ruby/install-deps
      - run: bundle exec rspec

  code_analysis:
    docker:
      - image: cimg/ruby:3.2.0
    steps:
      - checkout
      - ruby/install-deps
      - run: bundle exec rubocop
      - run: bundle exec brakeman
      # - run: bundle exec rake traceroute
      - run: bundle exec bundle-audit check --update
      - run: bundle exec rails_best_practices

  deploy_staging:
    docker:
      - image: cimg/ruby:3.2.0
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Deploy to Heroku Staging
          command: |
            git push https://heroku:${HEROKU_API_KEY}@git.heroku.com/atu-pipeline-staging.git $CIRCLE_BRANCH

  hold_for_approval:
    docker:
      - image: cimg/ruby:3.2.0
    steps:
      - run:
          name: Manual Approval Required
          command: echo "Manual approval required to merge develop into main."

  create_pull_request:
    docker:
      - image: cimg/ruby:3.2.0
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Create Pull Request on GitHub
          command: |
            curl -X POST -H "Authorization: token ${GITHUB_TOKEN}" -d '{"title":"Automated PR to Merge Develop into Main","body":"This PR is created automatically by the CI pipeline.","head":"develop","base":"main"}' https://api.github.com/repos/atu-devops/atu-pipeline-app/pulls

  deploy_production:
    docker:
      - image: cimg/ruby:3.2.0
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Deploy to Heroku Production
          command: |
            git push https://heroku:${HEROKU_API_KEY}@git.heroku.com/atu-pipeline.git $CIRCLE_BRANCH

workflows:
  version: 2

  test_analyze_and_deploy:
    jobs:
      - automated_tests
      - code_analysis:
          requires:
            - automated_tests
      - deploy_staging:
          requires:
            - code_analysis
      - hold_for_approval:
          type: approval
          requires:
            - deploy_staging
          filters:
            branches:
              only:
                - develop
      - create_pull_request:
          requires:
            - hold_for_approval
          filters:
            branches:
              only:
                - develop

  deploy_production:
    jobs:
      - deploy_production:
          filters:
            branches:
              only:
                - main
