version: 2.1

orbs:
  ruby: circleci/ruby@1.1.2

jobs:

  automated_tests:
    docker:
      - image: cimg/ruby:3.2.0 # Specify your Ruby version
    steps:
      - checkout
      - ruby/install-deps # Install dependencies
      - run:
          name: Run tests
          command: bundle exec rspec # Run RSpec tests

  code_analysis:
    docker:
      - image: cimg/ruby:3.2.0 # Specify the Ruby version
    steps:
      - checkout
      - ruby/install-deps # Install dependencies
      - run:
          name: Run RuboCop
          command: bundle exec rubocop # Run RuboCop static code analysis
      - run:
          name: Run Brakeman
          command: bundle exec brakeman
#      - run:
#          name: Check Routes with Traceroute
#          command: bundle exec rake traceroute
      - run:
          name: Check bundle for vulnerabilities
          command: bundle exec bundle-audit check --update
      - run:
          name: Run Rails Best Practices
          command: bundle exec rails_best_practices

  deploy_staging:
    docker:
      - image: cimg/ruby:3.2.0 # Specify your Ruby version
    steps:
      - checkout
      - ruby/install-deps # Install dependencies
      - run:
          name: Deploy to Heroku
          command: |
            git push https://heroku:${HEROKU_API_KEY}@git.heroku.com/atu-pipeline-staging.git $CIRCLE_BRANCH:develop
      - run:
          name: Wait for Approval
          command: echo "Waiting for approval to merge develop into main"

  hold_for_approval:
    docker:
      - image: cimg/ruby:3.2.0 # Specify your Ruby version
    steps:
      - checkout
      - ruby/install-deps # Install dependencies
      - run:
          name: Wait for Approval
          command: echo "Waiting for approval to merge develop into main"

  create_pull_request:
    docker:
      - image: cimg/ruby:3.2.0 # Specify your Ruby version
    steps:
      - checkout
      - ruby/install-deps # Install dependencies
      - run:
          name: Create Pull Request
          command: |
            curl -X POST -H "Authorization: token ${GITHUB_TOKEN}" -d '{"title":"Automated PR","body":"Automated PR","head":"develop","base":"main"}' https://api.github.com/repos/atu-pipeline/atu-pipeline/pulls
                      

  deploy_production:
    docker:
      - image: cimg/ruby:3.2.0 # Specify your Ruby version
    steps:
      - checkout
      - ruby/install-deps # Install dependencies
      - run:
          name: Deploy to Heroku
          command: |
            git push https://heroku:${HEROKU_API_KEY}@git.heroku.com/atu-pipeline.git $CIRCLE_BRANCH:main
        

workflows:
  version: 2
  test_and_analyze_developers_branches:
    jobs:
      - automated_tests
      - code_analysis:
          requires:
            - automated_tests
          filters:
            branches:
              ignore:
                - develop
                - main
                - "/^hotfix-.*$/"

  test_analyze_and_deploy:
    jobs:
      - automated_tests
      - code_analysis:
          requires:
            - automated_tests
      - deploy_staging:
          requires:
            - build
            - code_analysis
      - hold_for_approval:
          type: approval
          requires:
            - deploy_staging
          filters:
            branches:
              only:
                - develop
      - create_pull_request:
          requires:
            - hold_for_approval
          filters:
            branches:
              only:
                - develop
      - deploy_production:
          requires:
            - automated_tests
          filters:
            branches:
              only:
                - main



